SET DEFINE OFF;
Insert into BOOK
   (BOOK_ISBN, PUB_ID, BOOK_TITLE, BOOK_PRICE, BOOK_NBR_PGS)
 Values
   ('CA1256', 1, 'OPEN MIND', 200, 250);
Insert into BOOK
   (BOOK_ISBN, PUB_ID, BOOK_TITLE, BOOK_PRICE, BOOK_NBR_PGS)
 Values
   ('CA2256', 2, 'LORD OF RING', 300, 300);
Insert into BOOK
   (BOOK_ISBN, PUB_ID, BOOK_TITLE, BOOK_PRICE, BOOK_NBR_PGS)
 Values
   ('DA2056', 2, 'WIZARD', 400, 700);
Insert into BOOK
   (BOOK_ISBN, PUB_ID, BOOK_TITLE, BOOK_PRICE, BOOK_NBR_PGS)
 Values
   ('DA5256', 4, 'HARRY POTER', 200, 600);
Insert into BOOK
   (BOOK_ISBN, PUB_ID, BOOK_TITLE, BOOK_PRICE, BOOK_NBR_PGS)
 Values
   ('MA1256', 5, 'SHE', 300, 500);
COMMIT;
