SET DEFINE OFF;
Insert into BOOK_AUTHOR
   (BOOK_AUTHOR_ID, BOOK_ISBN, AUTHOR_ID, ROYALITY_RATE)
 Values
   (1, 'CA1256', 1, 10);
Insert into BOOK_AUTHOR
   (BOOK_AUTHOR_ID, BOOK_ISBN, AUTHOR_ID, ROYALITY_RATE)
 Values
   (2, 'CA2256', 2, 20);
Insert into BOOK_AUTHOR
   (BOOK_AUTHOR_ID, BOOK_ISBN, AUTHOR_ID, ROYALITY_RATE)
 Values
   (3, 'DA2056', 3, 25);
Insert into BOOK_AUTHOR
   (BOOK_AUTHOR_ID, BOOK_ISBN, AUTHOR_ID, ROYALITY_RATE)
 Values
   (4, 'DA5256', 4, 15);
Insert into BOOK_AUTHOR
   (BOOK_AUTHOR_ID, BOOK_ISBN, AUTHOR_ID, ROYALITY_RATE)
 Values
   (5, 'MA1256', 5, 30);
COMMIT;
