SET DEFINE OFF;
Insert into COURSES
   (COURSEID, COURSENAME, DURATION, CREDIT_HOURS, DEPT_ID, FACLT_ID)
 Values
   (1, 'MATH', 3, 60, 1, 1);
Insert into COURSES
   (COURSEID, COURSENAME, DURATION, CREDIT_HOURS, DEPT_ID, FACLT_ID)
 Values
   (2, 'COMPUTER SCIENCE', 4, 20, 1, 1);
Insert into COURSES
   (COURSEID, COURSENAME, DURATION, CREDIT_HOURS, DEPT_ID, FACLT_ID)
 Values
   (3, 'ENGLISH', 5, 30, 2, 2);
Insert into COURSES
   (COURSEID, COURSENAME, DURATION, CREDIT_HOURS, DEPT_ID, FACLT_ID)
 Values
   (4, 'SOCIAL SCIENCE', 6, 40, 3, 3);
Insert into COURSES
   (COURSEID, COURSENAME, DURATION, CREDIT_HOURS, DEPT_ID, FACLT_ID)
 Values
   (5, 'ARTS', 7, 50, 4, 2);
COMMIT;
