

-- Table Creation ---

CREATE TABLE AUTHOR
(
  AUTHOR_ID     NUMBER,
  AUTH_NAME     VARCHAR2(100 BYTE),
  AUTH_ADDRESS  VARCHAR2(150 BYTE)
);


CREATE TABLE BOOK
(
  BOOK_ISBN     VARCHAR2(50 BYTE),
  PUB_ID        NUMBER(10),
  BOOK_TITLE    VARCHAR2(100 BYTE),
  BOOK_PRICE    NUMBER(12,2),
  BOOK_NBR_PGS  NUMBER(10)
);


CREATE TABLE BOOK_AUTHOR
(
  BOOK_AUTHOR_ID  NUMBER(10),
  BOOK_ISBN       VARCHAR2(50 BYTE),
  AUTHOR_ID       NUMBER(10),
  ROYALITY_RATE   NUMBER(2)
);


CREATE TABLE PUBLISHER
(
  PUB_ID       NUMBER(10),
  PUB_NAME     VARCHAR2(100 BYTE),
  PUB_ADDRESS  VARCHAR2(150 BYTE),
  PUB_PHONE    VARCHAR2(30 BYTE)
);


CREATE TABLE ROYALTY_CHECK
(
  CHECK_NO        NUMBER(10),
  BOOK_AUTHOR_ID  NUMBER(10),
  CHECK_DATE      DATE,
  CHECK_AMOUNT    NUMBER(12,2)
);


CREATE UNIQUE INDEX AUTHOR_PK ON AUTHOR
(AUTHOR_ID);


CREATE UNIQUE INDEX BOOK_AUTHOR_PK ON BOOK_AUTHOR
(BOOK_AUTHOR_ID);


CREATE UNIQUE INDEX BOOK_PK ON BOOK
(BOOK_ISBN);


CREATE UNIQUE INDEX ROYALTY_CHECK_PK ON ROYALTY_CHECK
(CHECK_NO);



ALTER TABLE AUTHOR ADD (
  CONSTRAINT AUTHOR_PK
 PRIMARY KEY
 (AUTHOR_ID));

ALTER TABLE BOOK ADD (
  CONSTRAINT BOOK_PK
 PRIMARY KEY
 (BOOK_ISBN));

ALTER TABLE BOOK_AUTHOR ADD (
  CONSTRAINT BOOK_AUTHOR_PK
 PRIMARY KEY
 (BOOK_AUTHOR_ID));

ALTER TABLE PUBLISHER ADD (
  PRIMARY KEY
 (PUB_ID));

ALTER TABLE ROYALTY_CHECK ADD (
  CONSTRAINT ROYALTY_CHECK_PK
 PRIMARY KEY
 (CHECK_NO));

ALTER TABLE BOOK ADD (
  CONSTRAINT FK_PUB_ID 
 FOREIGN KEY (PUB_ID) 
 REFERENCES PUBLISHER (PUB_ID));

ALTER TABLE BOOK_AUTHOR ADD (
  CONSTRAINT FK_BOOK_ISBN 
 FOREIGN KEY (BOOK_ISBN) 
 REFERENCES BOOK (BOOK_ISBN),
  CONSTRAINT FK_AUTHOR_ID 
 FOREIGN KEY (AUTHOR_ID) 
 REFERENCES AUTHOR (AUTHOR_ID));

ALTER TABLE ROYALTY_CHECK ADD (
  CONSTRAINT FK_RBOOK_AUT_ID 
 FOREIGN KEY (BOOK_AUTHOR_ID) 
 REFERENCES BOOK_AUTHOR (BOOK_AUTHOR_ID));

