


CREATE TABLE INDUSTRIALUNIT
(
UNITID  	number(4) PRIMARY KEY,
LOCATION	varchar2(50),
COUNTRY		varchar2(50)
);


CREATE TABLE Product 
(
ProdId			number(4) PRIMARY KEY,
Desc			number(4), 
StdCostPerUnit	number(12,2), 
StdLabCostPerUnit	number(12,2)
);


CREATE TABLE  IndUnitProduct 
(UnitId		number(4),
ProdId		number(4)
);



CREATE TABLE  Employee 
(EmpId			number(4) PRIMARY KEY, 
EmpName			varchar2(100), 
YtdEarnings		varchar2(12,2), 
YtdTax			varchar2(4),
YtdNICont		varchar2(4), 
UnitId			number(4),
TaxCode			number(4)
);



CREATE TABLE  WorkOrder 
(WorkOrderId		number(4) PRIMARY KEY, 
Qty					number(4), 
UnitPrice			number(12,2), 
OrderDate			Date, 
PromiseDate			Date, 
CompDate			Date, 
ShipDate			Date, 
Status				varchar2(4),
ProdID				number(4)
);



CREATE TABLE LabourUsage 
(EmpId			number(4),  
WorkOrderId		number(4), 
WorkDate		Date, 
Hours			number(2), 
HourlyRate		number(4),  
Posted			CHAR(1)
);


ALTER TABLE IndUnitProduct
ADD CONSTRAINT FK_UnitId
FOREIGN KEY (UnitId) REFERENCES INDUSTRIALUNIT(UnitId); 

ALTER TABLE IndUnitProduct
ADD CONSTRAINT FK_ProdId
FOREIGN KEY (ProdId) REFERENCES Product(ProdId); 


ALTER TABLE LabourUsage
ADD CONSTRAINT FK_LabourUsage
FOREIGN KEY (EmpId) REFERENCES Employee(EmpId); 


ALTER TABLE LabourUsage
ADD CONSTRAINT FK_LabourUsage_WorkOrderId
FOREIGN KEY (WorkOrderId) REFERENCES WorkOrder(WorkOrderId); 


ALTER TABLE WorkOrder
ADD CONSTRAINT FK_WorkOrder_ProdId
FOREIGN KEY (ProdId) REFERENCES Product(ProdId); 


CREATE TABLE PROMOTIONS (
PROMO_ID	NUMBER(4) PRIMARY KEY,
PROMO_NAME	VARCHAR2(100),
PROMO_CATEGORY	VARCHAR2(50),
PROMO_COST		NUMBER(12,2),
PROMO_BEGIN_DATE	dATE,
PROMO_END_DATE		DATE
);


CREATE TABLE TIMES
(
TIME_ID	NUMBER(4) PRIMARY KEY,
DAY_NAME	VARCHAR2(25),
DAY_NUMBER_IN_WEEK	NUMBER(4),
DAY_NUMBER_IN_MONTH	NUMBER(4),
CALENDER_WEEK_NUMBER	NUMBER(4),
FISCAL_WEEK_NUMBER		NUMBER(4),
WEEK_ENDING_DAY	VARCHAR2(100),
CALENDER_MONTH_NUMBER	NUMBER(4),
FISCAL_MONTH_NUMBER	NUMBER(4),
FISCAL_MONTH_DESC	NUMBER(4),
DAYS_IN_CAL_MONTH	NUMBER(4),
DAYS_IN_FIS_MONTH	NUMBER(4),
END_OF_CAL_MONTH	NUMBER(4),
END_OF_FIS_MONTH	NUMBER(4),
CALENDER_MONTH_NAME	VARCHAR2(100),
FISCAL_MONTH_NAME	VARCHAR2(100),
CALENDER_QUARTER_DESC	VARCHAR2(100),
FISCAL_QUARTER_DESC  VARCHAR2(100),
DAYS_IN_CAL_QUARTER	NUMBER(4),
DAYS_IN_FIS_QUARTER	NUMBER(4),
END_OF_CAL_QUARTER	NUMBER(4),
END_OF_FIS_QUARTER	NUMBER(4),
CALENDER_QUARTER_NUMBER   NUMBER(4),
FISCAL_QUARTER_NUMBER     NUMBER(4),
CALENDER_YEAR    NUMBER(4),
FISCAL_YEAR   NUMBER(4),
DAYS_IN_CAL_YEAR	NUMBER(4),
DAYS_IN_FIS_YEAR	NUMBER(4),
END_OF_CAL_YEAR	NUMBER(4),
END_OF_FIS_YEAR  NUMBER(4)
);


CREATE TABLE COSTS
(
PROD_ID  NUMBER(4),
TIME_ID    NUMBER(4),
UNIT_COST   NUMBER(12,2),
UNIT_PRICE  NUMBER(12,2) 
);


CREATE TABLE SALES
(
PROD_ID    NUMBER(4),
CUST_ID   NUMBER(4),
TIME_ID    NUMBER(4),
CHANNEL_ID   NUMBER(4) ,
PROMO_ID     NUMBER(4),
QUANTITY_SOLD    NUMBER(4),
AMOUNT_SOLD		NUMBER(4)
);



CREATE TABLE CHANNELS
(
CHANNEL_ID    NUMBER(4) PRIMARY KEY,
CHANNEL_DESCRIPTION   varchar2(150) ,
CHANNEL_CLASS		varchar2(100)
);


CREATE TABLE PRODUCTS
(
PROD_ID   NUMBER(4) PRIMARY KEY,
PROD_NAME   varchar2(100) ,
PROD_DESC     varchar2(150),
PROD_SUBCATEGORY   varchar2(50) ,
PROD_SUBCAT_DESC   varchar2(100) ,
PROD_CATEGORY   varchar2(100) ,
PROD_CATEGORY_DESC  varchar2(100)  ,
PROD_WEIGHT_CLASS  varchar2(100)  ,
PROD_UNIT_OF_MEASURES  NUMBER(4)  ,
PROD_PACK_SIZE   varchar2(100),
SUPPLIER_ID   NUMBER(4),
PROD_STATUS   char(1),
PROD_LIST_PRICT   NUMBER(12,2) ,
PROD_MIN_PRICE		NUMBER(12,2)
);


CREATE TABLE CUSTOMERS
(
CUST_ID   NUMBER(4) PRIMARY KEY,
CUST_FIRST_NAME  varchar2(100) ,
CUST_LAST_NAME   varchar2(100),
CUST_GENDER    char(1),
CUST_YEAR_OF_birth  number(4)  ,
CUST_marital_status   varchar2(50),
CUST_STREET_ADDRESS  varchar2(150)  ,
CUST_POSTAL_CODE    varchar2(50)  ,
CUST_CITY    varchar2(50) ,
CUST_STATE_PROVINCE    varchar2(50),
CUST_MAIN_PHONE_NUMBER  varchar2(20)  ,
CUST_INCOME_LEVEL   NUMBER(4),
CUST_CREDIT_LIMIT  NUMBER(4) ,
CUST_EMAIL		varchar2(100)
);



CREATE TABLE COUNTRIES
(
COUNTRY_ID  NUMBER(4) PRIMARY KEY,
COUNTRY_NAME  varchar2(100)  ,
COUNTRY_SUNREGION  varchar2(50)  ,
COUNTRY_REGION varchar2(50)
);





















































































