DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER  (
  CUSTID  			NUMBER(10),
  CUSTLASTNAME  	VARCHAR2(100),
  CUSTFIRSTNAME  	VARCHAR2(100),
  CUSTADDRESS  		VARCHAR2(150),
  CUSTSTATE  		VARCHAR2(30),
  CUSTZIP  			VARCHAR2(30),
  CUSTEMAIL  		VARCHAR2(30),
  CUSTPHONE  		VARCHAR2(30),
  PRIMARY KEY (CUSTID)
);

DROP SEQUENCE SEQ_CUST_ID;

CREATE SEQUENCE SEQ_CUST_ID
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;


DROP TABLE SUPPLIER CASCADE CONSTRAINTS;

CREATE TABLE SUPPLIER  (
  SUPPID  			NUMBER(10),
  SUPPLASTNAME  	VARCHAR2(100),
  SUPPFIRSTNAME  	VARCHAR2(100),
  SUPPADDRESS  		VARCHAR2(150),
  SUPPSTATE  		VARCHAR2(30),
  SUPPZIP  			VARCHAR2(30),
  SUPPEMAIL   		VARCHAR2(30),
  SUPPPHONE  		VARCHAR2(30),
  PRIMARY KEY (SUPPID)
);


DROP SEQUENCE SEQ_SUPP_ID;

CREATE SEQUENCE SEQ_SUPP_ID
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT  (
  PRODID  			NUMBER(10),
  PRODNAME  		VARCHAR2(100),
  UNITPRICE  		NUMBER(12,2),
  EXPIREDATE  		DATE,
  PRODTYPE  		VARCHAR2(2),
  DESCRIPTION  		VARCHAR2(100),
  STOCK 			NUMBER(10),
  SUPPID 			NUMBER(10),
  PRIMARY KEY (PRODID)  
);


DROP SEQUENCE SEQ_PROD_ID;

CREATE SEQUENCE SEQ_PROD_ID
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
DROP TABLE STOCK CASCADE CONSTRAINTS;

CREATE TABLE STOCK  (
  STOCKID  			NUMBER(10),
  STOCKDATE  		DATE,
  DESCRIPTION  		VARCHAR2(100),
  PRODID  			NUMBER(10),
  QUANTITY  		NUMBER(10),
  REORDERLEVEL   	NUMBER(10),
  PRIMARY KEY (STOCKID)  
);


DROP SEQUENCE SEQ_STOCK_ID;

CREATE SEQUENCE SEQ_STOCK_ID
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 
DROP TABLE ORDERS CASCADE CONSTRAINTS;


CREATE TABLE ORDERS  (
  ORDERID  			NUMBER(10),
  ORDERDATE  		DATE,
  DESCRIPTION  		VARCHAR2(100),
  PRODID  			NUMBER(10),
  QUANTITY  		NUMBER(10),
  TOTALPRICE  		NUMBER(10),
  CUSTID  			NUMBER(10),
  PRIMARY KEY (ORDERID) ;
  
  ------------------
  
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (1,'ARAY', 'DIYA', 'NEWYORK', 'NY', 25632, 'ARAY@GMAIL.COM', '012-852-5632');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (2,'BERDAHL', 'TARA', 'NEWYORK', 'NY', 25632, 'KT874@MAIL.COM', '012-852-5633');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (3,'ESPINOZA', 'KERRY', 'NEWYORK', 'NY', 25632, 'ESPINOZA@MAIL.COM', '012-852-5634');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (4,'FLAKE', 'AARON', 'NEWYORK', 'NY', 25632, 'FLAKEA@MAIL.COM', '012-852-5635');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (5,'HOLDEN', 'LAUREN', 'NEWYORK', 'NY', 25632, 'HOLDEN238@MAIL.COM', '012-852-5636');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (1,'ARAY', 'DIYA', 'NEWYORK', 'NY', 25632, 'ARAY@GMAIL.COM', '012-852-5632');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (2,'BERDAHL', 'TARA', 'NEWYORK', 'NY', 25632, 'KT874@MAIL.COM', '012-852-5633');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (3,'ESPINOZA', 'KERRY', 'NEWYORK', 'NY', 25632, 'ESPINOZA@MAIL.COM', '012-852-5634');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (4,'FLAKE', 'AARON', 'NEWYORK', 'NY', 25632, 'FLAKEA@MAIL.COM', '012-852-5635');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (5,'HOLDEN', 'LAUREN', 'NEWYORK', 'NY', 25632, 'HOLDEN238@MAIL.COM', '012-852-5636');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (1,'ARAY', 'DIYA', 'NEWYORK', 'NY', 25632, 'ARAY@GMAIL.COM', '012-852-5632');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (2,'BERDAHL', 'TARA', 'NEWYORK', 'NY', 25632, 'KT874@MAIL.COM', '012-852-5633');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (3,'ESPINOZA', 'KERRY', 'NEWYORK', 'NY', 25632, 'ESPINOZA@MAIL.COM', '012-852-5634');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (4,'FLAKE', 'AARON', 'NEWYORK', 'NY', 25632, 'FLAKEA@MAIL.COM', '012-852-5635');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (5,'HOLDEN', 'LAUREN', 'NEWYORK', 'NY', 25632, 'HOLDEN238@MAIL.COM', '012-852-5636');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (1,'ARAY', 'DIYA', 'NEWYORK', 'NY', 25632, 'ARAY@GMAIL.COM', '012-852-5632');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (2,'BERDAHL', 'TARA', 'NEWYORK', 'NY', 25632, 'KT874@MAIL.COM', '012-852-5633');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (3,'ESPINOZA', 'KERRY', 'NEWYORK', 'NY', 25632, 'ESPINOZA@MAIL.COM', '012-852-5634');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (4,'FLAKE', 'AARON', 'NEWYORK', 'NY', 25632, 'FLAKEA@MAIL.COM', '012-852-5635');
INSERT INTO CUSTOMER (CUSTID, CUSTLASTNAME, CUSTFIRSTNAME, CUSTADDRESS, CUSTSTATE, CUSTZIP, CUSTEMAIL, CUSTPHONE)
VALUES (5,'HOLDEN', 'LAUREN', 'NEWYORK', 'NY', 25632, 'HOLDEN238@MAIL.COM', '012-852-5636');

-----------------

INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (1,'NAYAN', 'SUMI', 'NEWYORK', 'NY', 25632, 'NAYAN@YAHOO.COM', '012-852-5632');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (2,'KENNER', 'JASON', 'NEWYORK', 'NY', 25632, 'JKENNER@MAIL.COM', '012-852-5612');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (3,'MARTINEZ', 'EUGENE', 'NEWYORK', 'NY', 25632, 'EMARTINEZ@MAIL.COM', '012-852-5624');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (4,'NELSON', 'SHANE', 'NEWYORK', 'NY', 25632, 'NELSON_SHANE@MAIL.COM', '012-852-5662');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (5,'SHAW', 'DEBBY', 'NEWYORK', 'NY', 25632, 'DSHAW84@MAIL.COM', '012-852-5647');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (1,'NAYAN', 'SUMI', 'NEWYORK', 'NY', 25632, 'NAYAN@YAHOO.COM', '012-852-5632');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (2,'KENNER', 'JASON', 'NEWYORK', 'NY', 25632, 'JKENNER@MAIL.COM', '012-852-5612');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (3,'MARTINEZ', 'EUGENE', 'NEWYORK', 'NY', 25632, 'EMARTINEZ@MAIL.COM', '012-852-5624');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (4,'NELSON', 'SHANE', 'NEWYORK', 'NY', 25632, 'NELSON_SHANE@MAIL.COM', '012-852-5662');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (5,'SHAW', 'DEBBY', 'NEWYORK', 'NY', 25632, 'DSHAW84@MAIL.COM', '012-852-5647');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (1,'NAYAN', 'SUMI', 'NEWYORK', 'NY', 25632, 'NAYAN@YAHOO.COM', '012-852-5632');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (2,'KENNER', 'JASON', 'NEWYORK', 'NY', 25632, 'JKENNER@MAIL.COM', '012-852-5612');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (3,'MARTINEZ', 'EUGENE', 'NEWYORK', 'NY', 25632, 'EMARTINEZ@MAIL.COM', '012-852-5624');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (4,'NELSON', 'SHANE', 'NEWYORK', 'NY', 25632, 'NELSON_SHANE@MAIL.COM', '012-852-5662');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (5,'SHAW', 'DEBBY', 'NEWYORK', 'NY', 25632, 'DSHAW84@MAIL.COM', '012-852-5647');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (1,'NAYAN', 'SUMI', 'NEWYORK', 'NY', 25632, 'NAYAN@YAHOO.COM', '012-852-5632');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (2,'KENNER', 'JASON', 'NEWYORK', 'NY', 25632, 'JKENNER@MAIL.COM', '012-852-5612');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (3,'MARTINEZ', 'EUGENE', 'NEWYORK', 'NY', 25632, 'EMARTINEZ@MAIL.COM', '012-852-5624');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (4,'NELSON', 'SHANE', 'NEWYORK', 'NY', 25632, 'NELSON_SHANE@MAIL.COM', '012-852-5662');
INSERT INTO SUPPLIER ( SUPPID, SUPPLASTNAME, SUPPFIRSTNAME, SUPPADDRESS, SUPPSTATE, SUPPZIP, SUPPEMAIL, SUPPPHONE)
VALUES (5,'SHAW', 'DEBBY', 'NEWYORK', 'NY', 25632, 'DSHAW84@MAIL.COM', '012-852-5647');

----------------------


INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (1,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (2,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (3,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (4,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (5,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (1,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (2,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (3,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (4,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (5,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (1,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (2,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (3,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (4,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (5,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (1,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (2,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (3,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (4,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);
INSERT INTO PRODUCT(PRODID, PRODNAME, UNITPRICE, EXPIREDATE, PRODTYPE, DESCRIPTION, STOCK, SUPPID)
VALUES (5,'P1', 200, '01-JAN-2017', 'N', 'GOOD', 20, 1);

------------------------

INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (1,'25-OCT-2016', 'SHORT', 1,5, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (2,'25-OCT-2016', 'REORDER', 1,25, 15);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (3,'25-OCT-2016', 'SHORT', 1,20, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (4,'25-OCT-2016', 'SHORT', 1,35, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (5,'25-OCT-2016', 'SHORT', 1,45, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (1,'25-OCT-2016', 'SHORT', 1,5, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (2,'25-OCT-2016', 'REORDER', 1,25, 15);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (3,'25-OCT-2016', 'SHORT', 1,20, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (4,'25-OCT-2016', 'SHORT', 1,35, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (5,'25-OCT-2016', 'SHORT', 1,45, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (1,'25-OCT-2016', 'SHORT', 1,5, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (2,'25-OCT-2016', 'REORDER', 1,25, 15);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (3,'25-OCT-2016', 'SHORT', 1,20, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (4,'25-OCT-2016', 'SHORT', 1,35, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (5,'25-OCT-2016', 'SHORT', 1,45, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (1,'25-OCT-2016', 'SHORT', 1,5, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (2,'25-OCT-2016', 'REORDER', 1,25, 15);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (3,'25-OCT-2016', 'SHORT', 1,20, 10);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (4,'25-OCT-2016', 'SHORT', 1,35, 20);
INSERT INTO STOCK( STOCKID, STOCKDATE, DESCRIPTION, PRODID, QUANTITY, REORDERLEVEL)
VALUES (5,'25-OCT-2016', 'SHORT', 1,45, 20);

-----------------------
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (1,'25-OCT-2016', 'GOOD', 1,5,100,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (2,'25-OCT-2016', 'GOOD', 1,15,200,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (3,'25-OCT-2016', 'GOOD', 1,25,300,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (4,'25-OCT-2016', 'GOOD', 1,20,500,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (5,'25-OCT-2016', 'GOOD', 1,35,250,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (1,'25-OCT-2016', 'GOOD', 1,5,100,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (2,'25-OCT-2016', 'GOOD', 1,15,200,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (3,'25-OCT-2016', 'GOOD', 1,25,300,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (4,'25-OCT-2016', 'GOOD', 1,20,500,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (5,'25-OCT-2016', 'GOOD', 1,35,250,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (1,'25-OCT-2016', 'GOOD', 1,5,100,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (2,'25-OCT-2016', 'GOOD', 1,15,200,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (3,'25-OCT-2016', 'GOOD', 1,25,300,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (4,'25-OCT-2016', 'GOOD', 1,20,500,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (5,'25-OCT-2016', 'GOOD', 1,35,250,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (1,'25-OCT-2016', 'GOOD', 1,5,100,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (2,'25-OCT-2016', 'GOOD', 1,15,200,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (3,'25-OCT-2016', 'GOOD', 1,25,300,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (4,'25-OCT-2016', 'GOOD', 1,20,500,1);
INSERT INTO ORDERS  ( ORDERID, ORDERDATE, DESCRIPTION, PRODID, QUANTITY, TOTALPRICE, CUSTID) 
VALUES (5,'25-OCT-2016', 'GOOD', 1,35,250,1);

