SET DEFINE OFF;
Insert into DEPARTMENTS
   (DEPT_ID, DEPT_NAME, DEPT_PRIMARY_LOCATION, DEPT_ADDRESS, DEPT_SECONDARY_ADDRESS, DEPT_EMAIL, DEPT_PHONE, DEPT_FAX, FACLT_ID)
 Values
   (1, 'MATH', 'NY', 'NY', 'NY', 'math@usi.com', '444-222-5236', '4562-2356', 1);
Insert into DEPARTMENTS
   (DEPT_ID, DEPT_NAME, DEPT_PRIMARY_LOCATION, DEPT_ADDRESS, DEPT_SECONDARY_ADDRESS, DEPT_EMAIL, DEPT_PHONE, DEPT_FAX, FACLT_ID)
 Values
   (2, 'ENGLISH', 'NY', 'NY', 'NY', 'english@usi.com', '333-222-5236', '4562-2357', 1);
Insert into DEPARTMENTS
   (DEPT_ID, DEPT_NAME, DEPT_PRIMARY_LOCATION, DEPT_ADDRESS, DEPT_SECONDARY_ADDRESS, DEPT_EMAIL, DEPT_PHONE, DEPT_FAX, FACLT_ID)
 Values
   (3, 'COMPUTER SCIENCE', 'NY', 'NY', 'NY', 'cse@usi.com', '111-222-5236', '4562-2358', 1);
Insert into DEPARTMENTS
   (DEPT_ID, DEPT_NAME, DEPT_PRIMARY_LOCATION, DEPT_ADDRESS, DEPT_SECONDARY_ADDRESS, DEPT_EMAIL, DEPT_PHONE, DEPT_FAX, FACLT_ID)
 Values
   (4, 'SOCIAL SCIENCE', 'NY', 'NY', 'NY', 'sc@usi.com', '555-222-5239', '4562-2356', 1);
Insert into DEPARTMENTS
   (DEPT_ID, DEPT_NAME, DEPT_PRIMARY_LOCATION, DEPT_ADDRESS, DEPT_SECONDARY_ADDRESS, DEPT_EMAIL, DEPT_PHONE, DEPT_FAX, FACLT_ID)
 Values
   (5, 'ARTS', 'NY', 'NY', 'NY', 'arts@usi.com', '666-222-5232', '4562-2356', 1);
COMMIT;
